### ISSUE TITLE
INPUT_CONTACT_SELECT fields not appearing as recipient options for email workflow rules

### ISSUE THREAD

**Issue by jcreel** [TexasDigitalLibrary/Vireo#1114]
The INPUT_CONTACT ones do... but the INPUT_CONTACT_SELECT ones are not.

**Comment by StephanieVUGSC** [comment]
This sounds like something I am not able to see,  but I wanted to share what I observed today in the TDL test site because I believe it is related to this issue.    The potential Recipients currently listed in the email workflows are Submitter,  Assignee, Organization,  and Non-Chairing Committee members.   An obvious omission is the Committee Chair.    However,  when you look at some existing email workflow rules you see Recipients that are NOT in the current selection list.  Those include Committee Chair, Institution, and Director.   Perhaps these are the ones in an INPUT_CONTACT_SELECT field, but that is not anything I can observe from the end-user side.
