### ISSUE TITLE
Error Message : Destination is out of range

### ISSUE THREAD

**Issue by StephanieVUGSC** [TexasDigitalLibrary/Vireo#1223]
The error message "Destination is out of range" appears when re-ordering email templates.  Since the SYSTEM templates cannot be edited, institutions will prefer to order their templates so that the SYSTEM ones are the last in view.  

Reordering works, although the numbers do not change, so I am not sure what the error is. 
![image](https://user-images.githubusercontent.com/35782552/55247023-8d99c800-5214-11e9-8479-63da6135286e.png)

**Comment by kaladay** [comment]
This seems to happen when the an email template is removed.
Selecting any template whose number is higher than the number of the deleted email template throws this error. This error also happens on edit.

There is also a potentially related issue:
when the delete is cancelled most actions stop working because it is a "..dirty repo..". In the case of re-ordering, the console log shows "REORDER attempted on dirty repo".
