### ISSUE TITLE
BUG: Public display of filters is not working

### ISSUE THREAD

**Issue by StephanieVUGSC** [TexasDigitalLibrary/Vireo#1264]
The Administrator and Manager roles can create and save a Public filter that will be visible to other Administrators and Managers, but not reviewers.   

Currently, selecting the Public check box does not make the filter visible to others.  It only displays to the creator of the filter.

**Comment by StephanieVUGSC** [comment]
This feature is very important for institutions with decentralized ETD processing.

**Comment by jcross2562** [comment]
@cstarcher I've just found something "new", which I can see has been a problem for quite a while now. A few months ago, I created some filters and marked them as Public in the creation window, which is supposed to make them available for all admin/manager users. However, I've only just realized that they aren't visible to anyone else like they should be.

The first screenshot shows my list of filters, including the 3 that I've marked as Public (as evidenced by the globe).

![Screenshot 2023-04-21 132952](https://user-images.githubusercontent.com/127526737/233711138-beeceac6-92c2-4d45-ac48-8ff0505cb5f1.png)

But I asked one of my colleagues to login and send me a screenshot of what they see, and it's obvious that the filters are not visible to anyone else.

![ETDLists](https://user-images.githubusercontent.com/127526737/233711453-a9829171-e2da-4cda-8518-86210e7db1c9.png)

I think this might be a problem, so it probably should be routed as something important.

(I decided to add the comment here rather than create a new issue. I hope that's OK.)
