### ISSUE TITLE
Changing logo

### ISSUE THREAD

**Issue by ublrama** [TexasDigitalLibrary/Vireo#1409]
When changing the Vireo logo, you have to reset the log first before uploading a new log. When uploading a new logo without resetting the previous one, the following error occurs:

`Nov 27 09:15:10 vireo-a.web.leidenuniv.nl vireo4.sh[6742]: Detail: Key (name)=(left_logo) already exists.
Nov 27 09:15:10 vireo-a.web.leidenuniv.nl vireo4.sh[6742]: 2019-11-27 09:15:10.292 ERROR 6745 --- [nio-8080-exec-7] o.a.c.c.C.[.[.[/].[dispatcherServlet]    : Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed; nested exception is org.springframework.dao.DataIntegrityViolationException: could not execute statement; SQL [n/a]; constraint [uk1vlba62904n3irtnyokup860h]; nested exception is org.hibernate.exception.ConstraintViolationException: could not execute statement] with root cause
Nov 27 09:15:10 vireo-a.web.leidenuniv.nl vireo4.sh[6742]: org.postgresql.util.PSQLException: ERROR: duplicate key value violates unique constraint "uk1vlba62904n3irtnyokup860h"
Nov 27 09:15:10 vireo-a.web.leidenuniv.nl vireo4.sh[6742]: Detail: Key (name)=(left_logo) already exists.
`

**Comment by smutniak** [comment]
I was unable to replicate.

Done through Settings > Application > Look and Feel

changes files in resources/images/ (png, gif) originally set by
src/main/resources/settings/SYSTEM_Defaults.json in lookAndFeel json list

I uploaded a right and left logo.  I only saw right logo but no console errors.

**Comment by smutniak** [comment]
The first time a a left logo or right logo is set in Settings>Applications>LOOK_AND_FEEL it works according to the logos displayed on src/main/webapp/app/views/admin/settings/application/lookAndFeel.html.  I also verified that there were two new image files in target/classes/public/configuration/theme/ named left_logo.* and right_logo.*.  The database table managed_configuration had two new entries:
  
 id | name            | type        | value
...
  3 | left_logo       | lookAndFeel | public/configuration/theme/left_logo.jpeg
  4 | right_logo      | lookAndFeel | public/configuration/theme/right_logo.jpeg


Subsequent changes to those images results in an error in /src/main/java/org/tdl/vireo/controller/LookAndFeelController.java at line 61 where configurationRepo.create() is called.  The code just above it did update the files in target/** but this method fails because it attempts to insert duplicate entries in the name field (e.g left_logo).  
  
Next step: figure out a better weaver method to call on ConfigurationRepo or the weaver methods it invokes.
