### ISSUE TITLE
Version 4 Status?

### ISSUE THREAD

**Issue by misilot** [TexasDigitalLibrary/Vireo#1508]
Hi,

I am not sure if this is the best place to put this question. I was wondering what the status of Version 4 was? I saw that there was a RC released back in July 2019, and the blog post in October 2019, made it seem like version 4 was close to being released.

Thank you!

**Comment by cstarcher** [comment]
Thanks for your interest in Vireo 4. We have a production release ([4.1.0](https://github.com/TexasDigitalLibrary/Vireo/tree/4.1.0)) that is available for deployment. We just finished a sprint that fixed some outstanding issues, but we have not yet merged that into another release. That should be happening soon.

If you would like to stay up-to-date with Vireo announcements and have access to to the Vireo user community, you may join the Vireo User Group mailing list [here](https://utlists.utexas.edu/sympa/info/tdl-vireo).

**Comment by misilot** [comment]
Thanks @cstarcher, is there any chance have create a  tagged release in GitHub for 4.1.0 instead of just a specific branch?

Thanks again!

**Comment by cstarcher** [comment]
Yes, we will get that done.

**Comment by cstarcher** [comment]
@misilot,

Since we were in the middle of a sprint, we decided to wait to create a release for the next version. I am happy to report that version 4.1.1 has an official release. This version includes all of the code changes from the last sprint.

https://github.com/TexasDigitalLibrary/Vireo/releases/tag/v4.1.1
