### ISSUE TITLE
Identically named filters by multiple users duplicated in Now Filtering By

### ISSUE THREAD

**Issue by cstarcher** [TexasDigitalLibrary/Vireo#1781]
### Current behavior
When multiple users save a public filter with the same name, the filter appears multiple times under "Now filtering By" when one of the saved filters is applied.

### Expected behavior
Only the selected filter should show under "Now filtering By"

Discovered during work on PR #1778

**Comment by kaladay** [comment]
This might be solved by #1783.

**Comment by kaladay** [comment]
Investigation has shown that this problem is not that there are multiple filters being saved, instead it is that the same filter is being saved (overwritten) by multiple users.
When this happens, the properties are appended rather than replaced.

For example:
- User A: Creates a filter named `bob` and makes it public that excludes submission 1.
- User B: Creates a filter named `bob` and makes it public that excludes submission 2.

The end result is that a single named search filter group `bob` exists that has the filter criteria for excluding both submission 1 and submission 2.

There are two things to fix here:
1) The UI is separating the filters by user, creating multiple columns and is "duplicating" the "Now Filtering By".
2) The public filter is being saved with the same name as another public filter.

The solution to (1) is to do some sort of check to see if a "Now Filtering By" section is already added. The specific solution is dependent on the existing code.

There are multiple possible solutions to (2). The most straight-forward and simplest (if not ideal) solution would be to restrict saving public filters with the same name if another public filter already exists.

**Comment by kaladay** [comment]
> I see this as the best solution. Having multiple public filters with the same name is confusing.

@cstarcher 
Should I create a new issue to implement this solution or should I implement this solution as part of resolving this issue/spike?

**Comment by cstarcher** [comment]
@kaladay 
Go ahead and make a new issue so we can separate them. We'll leave this one just for the spike.

**Comment by kaladay** [comment]
The issue for preventing the save with same name as an existing public filter is now created here:
- https://github.com/TexasDigitalLibrary/Vireo/issues/1789
