### ISSUE TITLE
Deleted workflow steps not deleted from List View Customize Column

### ISSUE THREAD

**Issue by cstarcher** [TexasDigitalLibrary/Vireo#1876]
### Current behavior
When a user deletes an unused Field profile from a Workflow Step, the Field profile is not removed from the Customize columns list nor is the associated Metadata Key removed from the Workflow Management Metadata Keys.

### Expected behavior
An unused Field profile that has been deleted from all workflows should also be removed from the Customize columns list and the Workflow Management Metadata Keys.

### Steps to reproduce

1. Add a Field profile to a Workflow Step.
2. Remove Field profile from Workflow Step.
3. Open Customize columns modal in List view. The Field is still listed.
4. Open Metadata Keys under Workflow Management. The associated Metadata Key is still listed.

**Comment by labuchholz** [comment]
I think renaming a field also creates this problem--the old name stays in Customize columns, and the new name appears as an additional column. This means that saved filters have to be recreated with the new name. Expected behavior would be that the field is renamed in Customized columns and in column headers on List view, and that saved filters use the new.

**Comment by cstarcher** [comment]
I can confirm that renaming a Field profile does not update the name in the List View as stated above.

I could not reproduce the creation of an additional column for the renamed Field profile.
