### ISSUE TITLE
In the Admin item view replacing the primary document does not use a CV to control the allowed extensions.

### ISSUE THREAD

**Issue by wwelling** [TexasDigitalLibrary/Vireo#751]
In the admin item view, clicking "upload new file" then selecting "replace the primary document" opens a file select dialog without any restrictions on file type.

**Comment by nwoodward** [comment]
I'm trying to learn some Angular with this one. I get that the patterns attribute here can't be set with {{getPattern()} as in the field directive.

https://github.com/TexasDigitalLibrary/Vireo/blob/4.0.x/src/main/webapp/app/views/modals/view/addFileModal.html#L20

But if you change "pdf" to what it would be with a CV (".pdf") then the dragging a .txt file into the area will cause the file info fields to be blank, presumably because it's not an accepted pattern. But you're still able to submit the form and then it errors out. So it's like the pattern check works, but fileValidationError isn't set.

Would a potential solution be to build out the dropZone derivative to be more like fieldPredicate, with $scope.profile? Or should the form in the modal use the doctype_primary field predicate? Is the problem that the form is in a modal? I've added methods to the dropZone derivative, but only the dropMethodWrapper is called, and when it's called the only check is for zero files.

**Comment by jcreel** [comment]
Is this even a requirement for the Admin item view?  Perhaps we would want admins to upload any file types they want.

**Comment by StephanieVUGSC** [comment]
I don't believe you need to add file type validation to this one.  I agree with James, admins would prefer to upload any file types they want.    However does it matter in the submission view (admin side)?  When the admin uploads using "replace the primary document", the file becomes the PRIMARY document in the list of files in submission view.  When the student resubmits a corrected copy of the ETD as a PDF, the admin's file will change to ARCHIVED.

**Comment by kaladay** [comment]
The pattern matching is no longer restricting in the admin interface as of sprint32.
I am able to upload any type of file without restriction when adding a Primary Document as well as when replacing a Primary Document.

If any file other than a PDF is uploaded to a a Primary Document, both the student views and the admin views still display the Primary Document mime type as a PDF. This is misleading and either the mime types need to be detected instead of assumed to be PDF or the Primary Document should be restricted to only PDF.
